-- dua-wall Supabase 一键建表（在 Supabase SQL Editor 整段粘贴执行）
-- 1) 祈祷表
create table if not exists public.prayers (
  id bigint generated by default as identity primary key,
  name text,
  message text not null check (char_length(message) <= 140),
  created_at timestamptz not null default now()
);
alter table public.prayers enable row level security;
-- 匿名可读（墙是公开的）
create policy "anon read prayers" on public.prayers for select to anon using (true);
-- 匿名可写（只能插入，不能改/删）
create policy "anon insert prayers" on public.prayers for insert to anon with check (true);
-- 实时订阅（页面实时收到新祈祷）
alter publication supabase_realtime add table public.prayers;

-- 2) 浏览统计表 + 原子自增函数
create table if not exists public.stats (
  id int primary key default 1,
  views bigint not null default 0,
  constraint singleton check (id = 1)
);
insert into public.stats (id, views) values (1, 0) on conflict (id) do nothing;
alter table public.stats enable row level security;
create policy "anon read stats" on public.stats for select to anon using (true);
-- 不允许任何人直接改，只能通过函数自增
create or replace function public.bump_views()
returns void language plpgsql security definer set search_path = public as $$
begin
  insert into public.stats (id, views) values (1, 1)
  on conflict (id) do update set views = stats.views + 1;
end $$;
grant execute on function public.bump_views() to anon;
